name: Update Problem Counter Badge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Count Problems
      id: count_problems
      run: |
        python -c "
        import re
        from collections import defaultdict

        # Read the README file
        with open('README.md', 'r') as file:
            content = file.read()

        # Parse sections and problems
        sections = re.findall(r'## (.*?)\n\n\| Problem Name.*?\|.*?\n((?:\|.*?\|\n)+)', content, re.DOTALL)

        # Initialize counters
        difficulty_count = defaultdict(int)
        section_count = defaultdict(int)

        # Process each section
        for section, table in sections:
            problems = re.findall(r'\| .*? \| .*? \| .*? \| .*? \| (.*?) \|', table)
            section_count[section] = len(problems)
            for difficulty in problems:
                difficulty_count[difficulty] += 1

        # Generate the summary
        summary = '### Problems Solved Summary\n\n'
        summary += '#### By Difficulty:\n'
        for difficulty, count in difficulty_count.items():
            summary += f'- {difficulty}: {count} problems\n'

        summary += '\n#### By Section:\n'
        for section, count in section_count.items():
            summary += f'- {section}: {count} problems\n'

        # Insert the summary into the README file
        updated_content = re.sub(r'---\n', f'---\n\n{summary}\n', content, 1)

        # Write the updated README file
        with open('README.md', 'w') as file:
            file.write(updated_content)

        
        "

    - name: Upload Counter
      uses: actions/upload-artifact@v3
      with:
        name: counter
        path: counter.txt

    - name: Commit Updated Badge
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update problem counter badge
        branch: main
